apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app
        image: gcr.io/YOUR_PROJECT_ID/your-app-name:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "your-database-host"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "your-database-name"
        - name: DB_USER
          value: "your-database-user"
        - name: DB_PASSWORD
          value: "your-database-password"
