version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: finalP
      MYSQL_DATABASE: finalP
      MYSQL_USER: finalP
      MYSQL_PASSWORD: finalP
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: node-app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: finalP
      DB_USER: finalP
      DB_PASSWORD: finalP
      ACCESS_TOKEN_SECRET: 4qcc3S1dYE9nEOS8mbk6h3GYs75xqPNPOy4g1PDPeAc=
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql_data:

